export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_TIMES = 'FETCH_TIMES';
export const FETCH_TIME = 'FETCH_TIME';
export const FETCH_REPORT = 'FETCH_REPORT';

export const CREATE_TIME = 'CREATE_TIME';
export const CREATE_TIME_SUCCESS = 'CREATE_TIME_SUCCESS';
export const CREATE_TIME_FAIL = 'CREATE_TIME_FAIL';

export const UPDATE_TIME = 'UPDATE_TIME';
export const UPDATE_TIME_SUCCESS = 'UPDATE_TIME_SUCCESS';
export const UPDATE_TIME_FAIL = 'UPDATE_TIME_FAIL';


export const DELETE_TIME = 'UPDATE_TIME';
export const DELETE_TIME_SUCCESS = 'DELETE_TIME_SUCCESS';
export const DELETE_TIME_FAIL = 'DELETE_TIME_FAIL';
